name: eventhive
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  dio: ^5.7.0
  provider: ^6.1.2
  flutter_svg: ^2.0.13
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/lang/

    

  